# Generated by Django 4.2 on 2025-06-03 02:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True, verbose_name='房间号')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='是否入住')),
                ('current_temperature', models.FloatField(default=26.0, validators=[django.core.validators.MinValueValidator(16.0), django.core.validators.MaxValueValidator(30.0)], verbose_name='当前温度')),
                ('target_temperature', models.FloatField(default=26.0, validators=[django.core.validators.MinValueValidator(16.0), django.core.validators.MaxValueValidator(30.0)], verbose_name='目标温度')),
                ('ac_mode', models.CharField(choices=[('COOL', '制冷'), ('HEAT', '制热')], default='COOL', max_length=10, verbose_name='空调模式')),
                ('fan_speed', models.CharField(choices=[('LOW', '低速'), ('MEDIUM', '中速'), ('HIGH', '高速')], default='MEDIUM', max_length=10, verbose_name='风速')),
                ('is_ac_on', models.BooleanField(default=False, verbose_name='空调状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('LOW', '低'), ('MEDIUM', '中'), ('HIGH', '高')], default='MEDIUM', max_length=10, verbose_name='优先级')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('remaining_time', models.IntegerField(default=0, verbose_name='剩余时间(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_requests', to='core.room', verbose_name='房间')),
            ],
            options={
                'verbose_name': '服务队列',
                'verbose_name_plural': '服务队列',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(verbose_name='入住时间')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='退房时间')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='总费用')),
                ('is_paid', models.BooleanField(default=False, verbose_name='是否已支付')),
                ('payment_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='core.room', verbose_name='房间')),
            ],
            options={
                'verbose_name': '账单',
                'verbose_name_plural': '账单',
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='ACUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('start_temperature', models.FloatField(verbose_name='起始温度')),
                ('end_temperature', models.FloatField(blank=True, null=True, verbose_name='结束温度')),
                ('mode', models.CharField(choices=[('COOL', '制冷'), ('HEAT', '制热')], max_length=10, verbose_name='模式')),
                ('fan_speed', models.CharField(choices=[('LOW', '低速'), ('MEDIUM', '中速'), ('HIGH', '高速')], max_length=10, verbose_name='风速')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='持续时间')),
                ('energy_consumption', models.FloatField(default=0.0, verbose_name='能耗(kWh)')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='费用')),
                ('is_billed', models.BooleanField(default=False, verbose_name='是否已结算')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ac_usages', to='core.room', verbose_name='房间')),
            ],
            options={
                'verbose_name': '空调使用记录',
                'verbose_name_plural': '空调使用记录',
                'ordering': ['-start_time'],
            },
        ),
    ]
