# Generated by Django 4.2 on 2025-06-03 02:37

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'ordering': ['priority', 'request_time'], 'verbose_name': '服务队列请求', 'verbose_name_plural': '服务队列请求'},
        ),
        migrations.RemoveField(
            model_name='queue',
            name='remaining_time',
        ),
        migrations.AddField(
            model_name='queue',
            name='ac_mode',
            field=models.CharField(blank=True, choices=[('COOL', '制冷'), ('HEAT', '制热')], max_length=10, null=True, verbose_name='请求模式'),
        ),
        migrations.AddField(
            model_name='queue',
            name='fan_speed',
            field=models.CharField(blank=True, choices=[('LOW', '低速'), ('MEDIUM', '中速'), ('HIGH', '高速')], max_length=10, null=True, verbose_name='请求风速'),
        ),
        migrations.AddField(
            model_name='queue',
            name='request_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='请求时间'),
        ),
        migrations.AddField(
            model_name='queue',
            name='target_temperature',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(16.0), django.core.validators.MaxValueValidator(30.0)], verbose_name='请求目标温度'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='记录更新时间'),
        ),
    ]
