# Generated by Django 4.2 on 2025-06-03 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_queue_options_remove_queue_remaining_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', '客户'), ('reception', '前台'), ('admin', '管理员'), ('manager', '经理')], max_length=20)),
                ('room_number', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='访客姓名')),
                ('check_in_time', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='最后登录时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='core.room', verbose_name='房间')),
            ],
            options={
                'verbose_name': '访客',
                'verbose_name_plural': '访客',
                'ordering': ['-last_login'],
            },
        ),
    ]
