# Generated by Django 4.2 on 2025-06-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='id_number',
            field=models.CharField(default='', max_length=18, verbose_name='身份证号'),
        ),
    ]
