# Generated by Django 4.2.21 on 2025-06-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_guest_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退房时间'),
        ),
    ]
