# Generated by Django 4.2.21 on 2025-06-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_guest_check_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='check_in_count',
            field=models.IntegerField(default=1, verbose_name='入住次数'),
        ),
    ]
