# Generated by Django 4.2.21 on 2025-06-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_check_in_count'),
        ('core', '0006_guest_check_in_count'),
    ]

    operations = [
    ]
